
kind: Namespace
apiVersion: v1
metadata:
  name: ssmile
  labels:
    name: ssmile
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssmile-deployment
  namespace: ssmile
  labels:
    app: ssmile
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssmile
  template:
    metadata:
      labels:
        app: ssmile
    spec:
      nodeSelector:
        purpose: general
      containers:
      - name: ssmile
        image: charlie83gs/react_page:latest
        ports:
        - containerPort: 3000
      
---
apiVersion: v1
kind: Service
metadata:
  name: ssmile-service
  namespace: ssmile
spec:
  selector:
    app: ssmile
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: ssmile
  namespace: ssmile
spec:
  hosts:
  - "*"
  gateways:
  - istio-custom/devops-gateway
  http:
    - name: "ssmile-routes"
      match:
      - uri: 
          prefix: "/ssmile"
      route:
        - destination:
            host: ssmile-service.ssmile.svc.cluster.local

